from __future__ import annotations

from typing import Any


def _portal_bundle(
    *,
    display_name: str,
    login_url: str,
    homepage_url: str | None = None,
    source_url: str | None = None,
    source_note: str,
    constraints: str | None = None,
    timetable_support: str = "planned",
) -> dict[str, Any]:
    bundle: dict[str, Any] = {
        "shared_school_account": True,
        "display_name": display_name,
        "login_url": login_url,
        "homepage_url": homepage_url or login_url,
        "source_url": source_url or login_url,
        "source_note": source_note,
        "timetable_support": timetable_support,
    }
    if constraints:
        bundle["constraints"] = constraints
    return bundle


BUILTIN_MOODLE_SCHOOL_DIRECTORY: list[dict[str, Any]] = [
    {
        "school_slug": "yonsei_learnus",
        "display_name": "연세대학교 LearnUs",
        "ws_base_url": "https://ys.learnus.org/webservice/rest/server.php",
        "login_url": "https://ys.learnus.org/login.php",
        "homepage_url": "https://ys.learnus.org/",
        "source_url": "https://ys.learnus.org/login.php",
        "aliases": [
            "연세대학교",
            "연세대",
            "Yonsei",
            "Yonsei University",
            "LearnUs",
            "Yonsei LearnUs",
            "연세포털",
            "연세 포털",
            "연세포탈",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: LearnUs YONSEI",
            "portal": _portal_bundle(
                display_name="연세포털서비스",
                login_url="https://portal.yonsei.ac.kr/main/index.jsp",
                source_note="Official LearnUs guide and portal pages indicate LearnUs uses the same Yonsei portal account.",
                constraints="연세포털 시간표 페이지와 수강 데이터 엔드포인트는 아직 학교별 자동화가 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "pusan_plato",
        "display_name": "부산대학교 PLATO",
        "ws_base_url": "https://plato.pusan.ac.kr/webservice/rest/server.php",
        "login_url": "https://plato.pusan.ac.kr/login.php",
        "homepage_url": "https://plato.pusan.ac.kr/",
        "source_url": "https://plato.pusan.ac.kr/login.php",
        "aliases": [
            "부산대학교",
            "부산대",
            "Pusan National University",
            "PNU",
            "PLATO",
            "부산대학교 PLATO",
            "부산대 포털",
            "부산대학교 학생지원시스템",
            "onestop",
            "OneStop",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: 부산대학교 스마트 교육플랫폼 PLATO",
            "portal": _portal_bundle(
                display_name="부산대학교 학생지원시스템",
                login_url="https://onestop.pusan.ac.kr/",
                source_note="Official PNU pages route academic services through Onestop, and PLATO login guidance points students back to the same campus account flow.",
                constraints="학생지원시스템 시간표 API와 포털 세션 유지 방식은 아직 별도 검증이 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "gist_lms",
        "display_name": "광주과학기술원 GIST LMS",
        "ws_base_url": "https://lms.gist.ac.kr/webservice/rest/server.php",
        "login_url": "https://lms.gist.ac.kr/login.php",
        "homepage_url": "https://lms.gist.ac.kr/",
        "source_url": "https://lms.gist.ac.kr/login.php",
        "aliases": [
            "광주과학기술원",
            "GIST",
            "지스트",
            "GIST LMS",
            "GIST 포털",
            "지스트 포털",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: GIST LMS",
            "portal": _portal_bundle(
                display_name="GIST Portal",
                login_url="https://portal.gist.ac.kr/gateway/login.jsp",
                source_note="Official GIST guides say portal and LMS use the same GIST portal account and password.",
                constraints="포털 안의 학사/시간표 메뉴 구조와 세션 흐름은 아직 자동 수집 대상으로 분리 구현되지 않았습니다.",
            ),
        },
    },
    {
        "school_slug": "jbnu_lxp",
        "display_name": "전북대학교 JBNU LXP",
        "ws_base_url": "https://lms.jbnu.ac.kr/webservice/rest/server.php",
        "login_url": "https://lms.jbnu.ac.kr/login/index.php",
        "homepage_url": "https://lms.jbnu.ac.kr/",
        "source_url": "https://lms.jbnu.ac.kr/login/index.php",
        "aliases": [
            "전북대학교",
            "전북대",
            "JBNU",
            "JBNU LXP",
            "Jeonbuk National University",
            "전북대 포털",
            "오아시스",
            "OASIS",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS login page title: 사이트에 로그인 | JBNU LXP",
            "portal": _portal_bundle(
                display_name="전북대학교 포털 / OASIS",
                login_url="https://portal.jbnu.ac.kr/web/index.do",
                homepage_url="https://oasis.jbnu.ac.kr/",
                source_url="https://portal.jbnu.ac.kr/web/index.do",
                source_note="Official JBNU pages expose both the portal and OASIS academic system, and LMS login uses the same institutional account.",
                constraints="OASIS 수강시간표와 포털 세션은 별도 시스템이라 자동 연동 전에 엔드포인트 확인이 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "dongguk_eclass",
        "display_name": "동국대학교 이클래스",
        "ws_base_url": "https://eclass.dongguk.edu/webservice/rest/server.php",
        "login_url": "https://eclass.dongguk.edu/login.php",
        "homepage_url": "https://eclass.dongguk.edu/",
        "source_url": "https://eclass.dongguk.edu/login.php",
        "aliases": [
            "동국대학교",
            "동국대",
            "Dongguk",
            "Dongguk University",
            "이클래스",
            "eClass",
            "동국대 포털",
            "nDRIMS",
            "nPortal",
            "엔드림스",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: 동국대학교 이클래스",
            "portal": _portal_bundle(
                display_name="동국대학교 nPortal / nDRIMS",
                login_url="https://nportal.dongguk.edu/",
                homepage_url="https://ndrims.dongguk.edu/",
                source_url="https://nportal.dongguk.edu/",
                source_note="Official Dongguk pages route student information through nPortal and nDRIMS alongside eClass.",
                constraints="동국대 포털은 2차 인증이 개입할 수 있어 포털 세션 자동화와 시간표 수집이 바로 되지 않을 수 있습니다.",
            ),
        },
    },
    {
        "school_slug": "inu_lms",
        "display_name": "인천대학교 INU LMS",
        "ws_base_url": "https://cyber.inu.ac.kr/webservice/rest/server.php",
        "login_url": "https://cyber.inu.ac.kr/login.php",
        "homepage_url": "https://cyber.inu.ac.kr/",
        "source_url": "https://cyber.inu.ac.kr/login.php",
        "aliases": [
            "인천대학교",
            "인천대",
            "INU",
            "INU LMS",
            "Incheon National University",
            "인천대 포털",
            "인천대학교 포털",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: 인천대학교 학습관리시스템(INU LMS)",
            "portal": _portal_bundle(
                display_name="인천대학교 포털",
                login_url="https://portal.inu.ac.kr/login.jsp",
                source_note="Official INU portal pages expose portal login separately from LMS, and LMS guidance routes students through the same campus account.",
                constraints="포털 안의 개인 수강시간표 조회 경로와 데이터 형식은 아직 확인이 더 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "gachon_cyber_campus",
        "display_name": "가천대학교 Cyber Campus",
        "ws_base_url": "https://cyber.gachon.ac.kr/webservice/rest/server.php",
        "login_url": "https://cyber.gachon.ac.kr/login.php",
        "homepage_url": "https://cyber.gachon.ac.kr/",
        "source_url": "https://cyber.gachon.ac.kr/login.php",
        "aliases": [
            "가천대학교",
            "가천대",
            "Gachon",
            "Gachon University",
            "Cyber Campus",
            "가천대 포털",
            "가천대학교 포털",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: Cyber Campus",
            "portal": _portal_bundle(
                display_name="가천대학교 포털",
                login_url="https://portal.gachon.ac.kr/",
                source_note="Official Gachon guides expose both portal and Cyber Campus as campus services under the same student account flow.",
                constraints="포털 학사메뉴와 사이버캠퍼스의 시간표/강의실 데이터 연결점은 아직 학교별 조사 단계입니다.",
            ),
        },
    },
    {
        "school_slug": "sangmyung_ecampus",
        "display_name": "상명대학교 e-Campus",
        "ws_base_url": "https://ecampus.smu.ac.kr/webservice/rest/server.php",
        "login_url": "https://ecampus.smu.ac.kr/login.php",
        "homepage_url": "https://ecampus.smu.ac.kr/",
        "source_url": "https://ecampus.smu.ac.kr/login.php",
        "aliases": [
            "상명대학교",
            "상명대",
            "Sangmyung",
            "Sangmyung University",
            "SMU",
            "e-Campus",
            "상명대 포털",
            "샘물포털",
            "샘물 포털",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: 상명대학교 e-Campus",
            "portal": _portal_bundle(
                display_name="상명대학교 샘물포털",
                login_url="https://portal.smu.ac.kr/",
                source_note="Official Sangmyung pages identify portal.smu.ac.kr as 샘물포털 and use the same school account alongside e-Campus.",
                constraints="샘물포털 시간표/강의실 화면의 실제 조회 경로는 아직 자동화 전 단계입니다.",
            ),
        },
    },
    {
        "school_slug": "duksung_uclass",
        "display_name": "덕성여자대학교 U-Class",
        "ws_base_url": "https://lms.duksung.ac.kr/webservice/rest/server.php",
        "login_url": "https://lms.duksung.ac.kr/local/ubeclass/my.php",
        "homepage_url": "https://lms.duksung.ac.kr/",
        "source_url": "https://lms.duksung.ac.kr/local/ubeclass/my.php",
        "aliases": [
            "덕성여자대학교",
            "덕성여대",
            "덕성",
            "Duksung",
            "Duksung Women's University",
            "U-Class",
            "덕성 포털",
            "덕성여대 포털",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS login page title: 사이트에 로그인 | 덕성여자대학교 U-Class",
            "portal": _portal_bundle(
                display_name="덕성여자대학교 포털",
                login_url="https://portal.duksung.ac.kr/",
                source_note="Official Duksung pages list portal.duksung.ac.kr for campus login alongside U-Class.",
                constraints="포털 학사정보의 수강시간표 엔드포인트는 아직 확인 전이라 자동 시간표 동기화는 미구현입니다.",
            ),
        },
    },
    {
        "school_slug": "daejin_eclass",
        "display_name": "대진대학교 e-Class",
        "ws_base_url": "https://eclass.daejin.ac.kr/webservice/rest/server.php",
        "login_url": "https://eclass.daejin.ac.kr/login.php?lang=en&sso=ok",
        "homepage_url": "https://eclass.daejin.ac.kr/",
        "source_url": "https://eclass.daejin.ac.kr/login.php?lang=en&sso=ok",
        "aliases": [
            "대진대학교",
            "대진대",
            "Daejin",
            "Daejin University",
            "e-Class",
            "대진대 포털",
            "포털대진",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS login page title: 로그인 [차세대 e-Class System]",
            "portal": _portal_bundle(
                display_name="대진대학교 포털대진",
                login_url="https://www.daejin.ac.kr/daejin/intro/intro_04.do",
                homepage_url="https://www.daejin.ac.kr/",
                source_url="https://www.daejin.ac.kr/daejin/intro/intro_04.do",
                source_note="Official Daejin user guides describe 포털대진 as the entry point after the university homepage login.",
                constraints="직접 로그인 URL과 세션 흐름이 공개 페이지에서 명확하지 않아, 포털 자동 로그인은 별도 런타임 검증이 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "uos_portal",
        "display_name": "서울시립대학교 포털/대학행정",
        "ws_base_url": "https://wise.uos.ac.kr/index.do",
        "login_url": "https://portal.uos.ac.kr/p/STUD/",
        "homepage_url": "https://portal.uos.ac.kr/p/STUD/",
        "source_url": "https://wise.uos.ac.kr/index.do",
        "aliases": [
            "서울시립대학교 포털",
            "서울시립대 포털",
            "시립대 포털",
            "UOS 포털",
            "UOS portal",
            "WISE",
            "이루넷",
        ],
        "metadata_json": {
            "provider": "uos_portal",
            "auth_mode": "browser_session",
            "country_code": "KR",
            "source_checked_at": "2026-03-11",
            "source_note": "Student guide documents say portal general login links to WISE via GNB SSO, and WISE directLogin uses a one-time password as fallback only.",
            "portal": _portal_bundle(
                display_name="서울시립대학교 포털/대학행정",
                login_url="https://portal.uos.ac.kr/p/STUD/",
                homepage_url="https://wise.uos.ac.kr/index.do",
                source_url="https://wise.uos.ac.kr/index.do",
                source_note="Student guide documents say portal login opens WISE through GNB SSO.",
                constraints="시립대는 포털 세션과 시간표 파싱까지 이미 구현되어 있습니다.",
                timetable_support="supported",
            ),
        },
    },
    {
        "school_slug": "uos_online_class",
        "display_name": "서울시립대학교 온라인강의실",
        "ws_base_url": "https://uclass.uos.ac.kr/webservice/rest/server.php",
        "login_url": "https://uclass.uos.ac.kr/login/index.php",
        "homepage_url": "https://uclass.uos.ac.kr/",
        "source_url": "https://uclass.uos.ac.kr/login/index.php",
        "aliases": [
            "서울시립대학교",
            "서울시립대",
            "시립대",
            "UOS",
            "UOS 온라인강의실",
            "서울시립대학교 온라인강의실",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official login page title: 사이트에 로그인 | 서울시립대학교 온라인강의실",
            "auth_note": "Official Moodle token endpoint is reachable and returns invalidlogin for bad credentials, confirming token-based login path is live.",
            "portal": _portal_bundle(
                display_name="서울시립대학교 포털/대학행정",
                login_url="https://portal.uos.ac.kr/p/STUD/",
                homepage_url="https://wise.uos.ac.kr/index.do",
                source_url="https://wise.uos.ac.kr/index.do",
                source_note="Student guide documents say portal login opens WISE through GNB SSO.",
                constraints="시립대는 포털 세션과 시간표 파싱까지 이미 구현되어 있습니다.",
                timetable_support="supported",
            ),
        },
    },
    {
        "school_slug": "kaist_klms",
        "display_name": "KAIST KLMS",
        "ws_base_url": "https://klms.kaist.ac.kr/webservice/rest/server.php",
        "login_url": "https://klms.kaist.ac.kr/",
        "homepage_url": "https://klms.kaist.ac.kr/",
        "source_url": "https://celt.kaist.ac.kr/krcelt/html/sub04/0401.html",
        "aliases": [
            "KAIST",
            "카이스트",
            "한국과학기술원",
            "KLMS",
            "KAIST KLMS",
            "카이스트 포털",
            "KAIST portal",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official CELT page says KLMS is the Moodle-based KAIST LMS and links to https://klms.kaist.ac.kr.",
            "auth_note": "Official LMS confirmed, but portal-linked SSO may require runtime verification for ID/PW token issuance.",
            "portal": _portal_bundle(
                display_name="KAIST Portal",
                login_url="https://portal.kaist.ac.kr/",
                source_url="https://portal.kaist.ac.kr/",
                source_note="Official KAIST guides state KLMS uses the same portal ID for login.",
                constraints="포털/학사시스템 시간표 API와 KLMS SSO 결합은 아직 학교별 구현이 필요합니다.",
            ),
        },
    },
    {
        "school_slug": "hallym_smartlead",
        "display_name": "한림대학교 SmartLEAD",
        "ws_base_url": "https://smartlead.hallym.ac.kr/webservice/rest/server.php",
        "login_url": "https://smartlead.hallym.ac.kr/login.php",
        "homepage_url": "https://smartlead.hallym.ac.kr/",
        "source_url": "https://smartlead.hallym.ac.kr/login.php",
        "aliases": [
            "한림대학교",
            "한림대",
            "Hallym",
            "Hallym University",
            "SmartLEAD",
            "한림대 포털",
            "한림포털",
            "통합정보시스템",
        ],
        "metadata_json": {
            "country_code": "KR",
            "source_checked_at": "2026-03-12",
            "source_note": "Official LMS landing page title: 한림SmartLEAD",
            "portal": _portal_bundle(
                display_name="한림대학교 포털 / 통합정보시스템",
                login_url="https://portal.hallym.ac.kr/",
                homepage_url="https://was1.hallym.ac.kr:8087/",
                source_url="https://portal.hallym.ac.kr/",
                source_note="Official Hallym pages expose both portal.hallym.ac.kr and the integrated information system alongside SmartLEAD.",
                constraints="한림대 포털의 실제 시간표 조회 URL과 응답 형식은 아직 별도 조사 대상입니다.",
            ),
        },
    },
]
